#!/usr/bin/env bash

# To prevent poetry from asking to unlock keyring (thus preventing issue of installation never finishing)
# this workaround is needed see  https://github.com/python-poetry/poetry/issues/5250 or https://stackoverflow.com/questions/74438817/poetry-failed-to-unlock-the-collection
export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
poetry install
